service_account_key: service_account_key.json
project: noorahealth-raw
environments:
  - name: prod
    dataset: ccp_andhra_pradesh
  - name: dev
    dataset: ccp_andhra_pradesh_dev
slack_channel_id: C080138T9S6
