name: Sync Data to BigQuery

on:
  schedule:
    - cron: '20 19 * * *'

jobs:
    sync-data-to-bq:
        runs-on: ubuntu-latest
        env:
            API_USERNAME: ${{ secrets.USERNAME }}
            API_PASSWORD: ${{ secrets.PASSWORD }}
            API_URL: ${{ vars.API_URL }}
            SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
            SLACK_RECEIVER_ID: ${{ vars.SLACK_RECEIVER_ID }}
            BQ_DATASET_NAME: ${{ vars.BIGQUERY_DATASET_NAME }}
            BQ_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.12'
            cache: 'pip'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run script
          run: python api_export.py --mode bq
