name: Fetch Today's Data

on:
  schedule:
    - cron: '20 19 * * *'

jobs:
  fetch-daily-data:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API_URL: ${{ vars.API_URL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_RECEIVER_ID: ${{ vars.SLACK_RECEIVER_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python api-export.py

      - name: Get current date
        id: date
        run: echo "release_name=$(date +'%d-%m-%Y')" >> "$GITHUB_OUTPUT"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: data.xlsx
          tag_name: ${{ steps.date.outputs.release_name }}
