name: Send Weekly Report on Slack

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '20 19 * * *'

jobs:
  send-weekly-report-on-slack:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        API_URL: ${{ vars.API_URL }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        SLACK_RECEIVER_ID: ${{ vars.SLACK_RECEIVER_ID }}
        BIGQUERY_SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python api-export.py --mode report
