name: Send Data on Slack

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '55 22 * * 0'

jobs:
  send-on-slack:
    runs-on: ubuntu-latest
    env:
      API_PARAMS: ${{ secrets.API_PARAMS }}
      SLACK_PARAMS: ${{ secrets.SLACK_PARAMS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python -u api_export.py --dest slack
