name: Sync Andhra Pradesh MLHP

on:
  schedule:
    - cron: '30 18 * * 3'
  workflow_dispatch:
    inputs:
      timeout_mins:
        required: false
        type: choice
        options:
          - 5
          - 20
          - 60
          - 240
      trigger_mode:
        required: false
        type: choice
        options:
          - oneanddone
          - oneormore
          - continuing

jobs:
  sync-to-warehouse:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
      SOURCE_PARAMS: ${{ secrets.ANDHRA_PRADESH_MLHP }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      TIMEOUT_MINS: ${{ inputs.timeout_mins || (github.event_name == 'pull_request' && '5' || '240') }}
      TRIGGER_MODE: ${{ inputs.trigger_mode || (github.event_name == 'pull_request' && 'oneanddone' || 'oneormore') }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Run script
        run: uv run -m src.andhra_pradesh_mlhp --timeout-mins $TIMEOUT_MINS --trigger-mode $TRIGGER_MODE
