name: Sync Data to BigQuery

on:
  # push:
  #   branches:
  #     - 'main'
  schedule:
    - cron: '50 18 * * 0'
  pull_request:
  workflow_dispatch:

jobs:
  sync-to-bigquery:
    runs-on: ubuntu-latest
    env:
      API_PARAMS: ${{ secrets.API_PARAMS }}
      BIGQUERY_SERVICE_ACCOUNT_KEY: ${{ secrets.BIGQUERY_SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Run script
        run: uv run api_export.py --dest bigquery
