name: Sync Andhra Pradesh CCP

on:
  schedule:
    - cron: '30 18 * * 0'
  workflow_dispatch:

jobs:
  sync-to-warehouse:
    runs-on: ubuntu-latest
    env:
      ANDHRA_PRADESH_CCP: ${{ secrets.ANDHRA_PRADESH_CCP }}
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync

      - name: Run script
        run: uv run sync/andhra_pradesh_ccp.py
